[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Butterfly = "300f4b98-7452-4879-8417-07ff5a8f26cb"
FINUFFT = "d8beea63-0952-562e-9c6a-8e8ef7364055"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
LowRankApprox = "898213cb-b102-5a47-900c-97e73b919f73"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Morton = "2a6d852e-3fac-5a38-885c-fe708af2d09e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RegionTrees = "dee08c22-ab7f-5625-9660-a9af2021b33f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SphericalHarmonics = "c489a379-e885-57ff-9236-bd896d33c250"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
